language: node_js
sudo: required
node_js:
  - '0.10'

install:
  - npm config set spin false
  - npm config set loglevel http
  - npm install -g npm
  - npm install
  - npm install -g bower
  - gem install compass
  - sudo pip install awscli

before_script:
  - npm install -g grunt-cli
  - bower install
  - grunt build

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  bucket: $BUCKET
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  on:
    branch: master
