language: node_js
sudo: false
node_js:
  - '0.10'

install:
  - npm config set spin false
  - npm config set loglevel http
  - npm install -g npm
  - npm install

before_script:
  - npm install -g grunt-cli
  - grunt build
