language: node_js
sudo: false
node_js:
  - '0.10'

install:
  - npm config set spin false
  - npm config set loglevel http
  - npm install -g npm
  - npm install
  - npm install -g bower
  - gem install compass
  - python get-pip.py
  - pip install awscli
  -

before_script:
  - npm install -g grunt-cli
  - bower install
  - grunt build

deploy:
  skip_cleanup: true
  - aws s3 rm s3://$BUCKET/ --recursive
  - aws s3 cp dist/ s3://$BUCKET/ --recursive --acl public-read
